### ISSUE TITLE
Installation fail on MacOS

### ISSUE THREAD

**Issue by charlesneimog** [charlesneimog/py4pd#66]
See #65,

Hi, I'm using Mac Intel 10.14.6, I installed Python 3.11 before but it didn't work using external

![285267847-cad84d66-6d61-455d-968e-34ff0060b8e6](https://github.com/charlesneimog/py4pd/assets/31707161/42913827-3612-4147-bfe5-44cdf780698b)

**Comment by charlesneimog** [comment]
@porres, vc instalou usando esse executável aqui?

https://www.python.org/downloads/release/python-3116/

Não pode ser o `3.12`.

**Comment by porres** [comment]
ah, peguei o ultimo estavel... nem vi qual, achei que er ao 3.11, mas foi esse de outubro https://www.python.org/downloads/release/python-3120/

**Comment by porres** [comment]
como faz pra desinstalar agora, instalo esse 3.11.6?

**Comment by porres** [comment]
fecha aí que agora deu certo!!!
