### ISSUE TITLE
Broken link in py4pd.help.pd

### ISSUE THREAD

**Issue by martindupras** [charlesneimog/py4pd#87]
in file 
resources/py4pd-help.pd

line 194:
#X text 292 160 IMPORTANT: This is just simple example \, the exaustive Docs are avaible in www.charlesneimog.github.io/py4pd;

should be replaced with:
#X text 292 160 IMPORTANT: This is just simple example \, the exhaustive Docs are available in charlesneimog.github.io/py4pd;

**Comment by charlesneimog** [comment]
thanks!
